name: frontend-stack

services:
  frontend-web:
    build:
      context: ./app/frontend
    ports:
      - "${FRONTEND_WEB_PORT:-5173}:5173"
    environment:
      NODE_ENV: production
    command: npm run preview -- --host 0.0.0.0 --port 5173
    restart: unless-stopped
